services:
  - type: web
    name: github-code-analysis-ai
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p /opt/render/.cache/ms-playwright
      chmod -R 777 /opt/render/.cache/ms-playwright
      PLAYWRIGHT_BROWSERS_PATH=/opt/render/.cache/ms-playwright playwright install chromium --with-deps
    startCommand: |
      PLAYWRIGHT_BROWSERS_PATH=/opt/render/.cache/ms-playwright \
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0 \
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 10000
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "0"
