services:
  - type: web
    name: github-code-analysis-ai
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      mkdir -p $HOME/.cache/ms-playwright
      PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/ms-playwright playwright install chromium --with-deps
      chmod -R 777 $HOME/.cache/ms-playwright
    startCommand: |
      PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/ms-playwright \
      gunicorn --timeout 120 --workers 1 --threads 2 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 10000
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "$HOME/.cache/ms-playwright"
